### ISSUE TITLE
Bug: Program throws error message when GitHub is not checked

### ISSUE THREAD

**Issue by NChechulin** [skyrunner360/Code_Friend#7]
The program shows message that you have to select an option (even when some of them are selected) if user doesn't check the GitHub checkbox.

**Comment by skyrunner360** [comment]
I'm aware of this bug. you can contribute to solving it if you feel like.

**Comment by NChechulin** [comment]
I'm working with the codebase right now. I guess, I'll send a Pull Request 2-3 hours later, which fixes all of issues opened by me.

**Comment by skyrunner360** [comment]
ok. Cool!

**Comment by NChechulin** [comment]
I sent the Pull Request. I'll close the issues after accept.

**Comment by skyrunner360** [comment]
Done merging changes. Thanks a Lot Mate for contributing here!!

**Comment by NChechulin** [comment]
FIxed
